name: word_memorizer
description: A Flutter app for memorizing words with speech repetition.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  flutter_local_notifications: ^14.0.0+2
  url_launcher: ^6.1.10
  shared_preferences: ^2.3.5
  words: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

